/**
 * Single source of truth for the site's public identity.
 *
 * Canonical host: www.quantumsynclabs.com
 * The apex domain 301s here (see vercel.json). Both hosts previously served
 * 200, which split ranking signals between two copies of every page.
 *
 * To switch to the apex domain, change SITE_URL here, set VITE_APP_URL to match
 * in the deployment environment, and flip the redirect in vercel.json.
 */
export const SITE_URL = (
  import.meta.env.VITE_APP_URL || "https://www.quantumsynclabs.com"
).replace(/\/$/, "");

export const SITE_NAME = "QuantumSync Labs";

export const SITE_DESCRIPTION =
  "Empowering digital transformation through innovative, secure, and scalable IT solutions.";

/** Default Open Graph card, generated by scripts/generate-og-image.mjs */
export const DEFAULT_OG_IMAGE = "/og-image.webp";

export const CONTACT = {
  email: "labsquantumsync@gmail.com",
  phone: "+94741240337",
  phoneDisplay: "+94 741 240 337",
};

export const SOCIAL_PROFILES = [
  "https://www.linkedin.com/company/quantumsync-labs",
  "https://github.com/QuantumSync-Labs-PLC/",
  "https://www.facebook.com/quantumsynclabs",
  "https://www.instagram.com/quantumsync_labs",
];

/** Build an absolute URL from a site-relative path. */
export function absoluteUrl(path = "/") {
  if (!path) return SITE_URL;
  if (path.startsWith("http")) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}
