/**
 * Generates public/sitemap.xml from the real route data.
 *
 * The hand-written sitemap this replaces listed /services/1..4 and /blog/1..2,
 * which 404 because the router matches slugs, and omitted /work, every case
 * study, three services and six blog posts. Deriving it from the data files
 * means it can never drift from the routes again.
 *
 * Run: node scripts/generate-sitemap.mjs   (also runs automatically on build)
 */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { loadRouteData } from "./routeList.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const SITE_URL = (
  process.env.VITE_APP_URL || "https://www.quantumsynclabs.com"
).replace(/\/$/, "");

const { navRoutes, services, caseStudies, blogPosts } = await loadRouteData();

const today = new Date().toISOString().slice(0, 10);

// Per-path tuning; anything in the nav that isn't listed gets sensible defaults,
// so a new page is indexed the moment it's added to constants/routes.js.
const STATIC_HINTS = {
  "/": { changefreq: "weekly", priority: "1.0" },
  "/services": { changefreq: "monthly", priority: "0.9" },
  "/work": { changefreq: "monthly", priority: "0.9" },
  "/pricing": { changefreq: "monthly", priority: "0.9" },
  "/process": { changefreq: "monthly", priority: "0.8" },
  "/contact": { changefreq: "monthly", priority: "0.8" },
  "/blog": { changefreq: "weekly", priority: "0.8" },
  "/careers": { changefreq: "weekly", priority: "0.7" },
};

/** @type {{path: string, changefreq: string, priority: string, lastmod?: string}[]} */
const urls = [
  ...navRoutes.map((route) => ({
    path: route.path,
    changefreq: STATIC_HINTS[route.path]?.changefreq || "monthly",
    priority: STATIC_HINTS[route.path]?.priority || "0.7",
  })),

  ...services.map((s) => ({
    path: `/services/${s.id}`,
    changefreq: "monthly",
    priority: "0.8",
  })),

  ...caseStudies.map((c) => ({
    path: `/work/${c.id}`,
    changefreq: "monthly",
    priority: "0.8",
  })),

  ...blogPosts.map((p) => ({
    path: `/blog/${p.id}`,
    changefreq: "monthly",
    priority: "0.6",
    lastmod: p.date,
  })),
];

const seen = new Set();
for (const u of urls) {
  if (seen.has(u.path)) throw new Error(`Duplicate sitemap URL: ${u.path}`);
  seen.add(u.path);
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${SITE_URL}${u.path}</loc>
    <lastmod>${u.lastmod || today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join("\n")}
</urlset>
`;

writeFileSync(join(root, "public/sitemap.xml"), xml, "utf8");
console.log(
  `Wrote public/sitemap.xml — ${urls.length} URLs ` +
    `(${navRoutes.length} pages, ${services.length} services, ` +
    `${caseStudies.length} case studies, ${blogPosts.length} posts) at ${SITE_URL}`
);
